### PR TITLE
[PA-6145]: Applied Curl Patch CVE-2023-46218

### PR DESCRIPTION
**Pull request by span786**
Applied Curl Patch CVE-2023-46218 [cookie: lowercase the domain names before PSL checks]

### CODE REVIEW

**Review by joshcooper — APPROVED** [review]
If you haven't already, could you try to run vanagon generic builder on a subset of platforms including windows, solaris, aix, mac and linux

**Comment by span786** [comment]
vanagon-generic-builder pipeline links:
1. [agent-runtime-main](https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2749/) : Build is failing for solaris-11-sparc because of error (../src/sparc/ffi.c:319:3: error: 'asm' undeclared (first use in this function))
2. [agent-runtime-7.x](https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2750/) : Build is failing for aix-7.2-ppc because of error (/bin/sh: /opt/pl-build-tools/bin/gcc:  not found)

**Comment by joshcooper** [comment]
@span786 I think you're mixing BUILD_TARGETS from `agent-runtime-7.x` and `agent-runtime-main` Unfortunately, they're similar, but not the same, so be sure you're copying the BUILD_TARGETS from the correct `agent-runtime-*` Init job.

[7.x Init](https://jenkins-platform.delivery.puppetlabs.net/view/puppet-runtime/view/agent-runtime-7.x/job/platform_agent-runtime_runtime-vanagon-init_7.x/)
[main Init](https://jenkins-platform.delivery.puppetlabs.net/view/puppet-runtime/view/agent-runtime-main/job/platform_agent-runtime_runtime-vanagon-init_main/)

For Solaris 11 SPARC, we native compile in main, but cross compile in 7.x. So when building `agent-runtime-main`, you'll want to use this [`solaris-11-native-sparc`](https://github.com/puppetlabs/ci-job-configs/blob/17d55bf9b75dce4188969bed9d6fb379022159ee/jenkii/platform/projects/puppet-agent.yaml#L269), which refers to this [platform definintion](https://github.com/puppetlabs/puppet-runtime/blob/master/configs/platforms/solaris-11-native-sparc.rb). This is necessary, because we needed newer gcc and build tools to compile ruby 3.2, etc.

For AIX, `agent-runtime-7.x` builds on [`AIX 7.1`](https://github.com/puppetlabs/ci-job-configs/blob/17d55bf9b75dce4188969bed9d6fb379022159ee/jenkii/platform/projects/puppet-agent.yaml#L218) while `agent-runtime-main` builds on [`AIX 7.2`](https://github.com/puppetlabs/ci-job-configs/blob/17d55bf9b75dce4188969bed9d6fb379022159ee/jenkii/platform/projects/puppet-agent.yaml#L250). This is because AIX 7.1 is technically EOL and so we didn't want to start off building puppet 8, ruby 3.2, etc on an EOL platform. Note AIX is like Windows, we build on the oldest supported platform, but install on all supported platforms like 7.2 and 7.3.
